[project]
name = "clickup-ai-analysis"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "altair>=5.5.0",
    "dotenv>=0.9.9",
    "google-genai>=1.31.0",
    "pandas>=2.3.2",
    "streamlit>=1.50.0",
]
